"""Shared signal lookbacks and Turkish fundamental sheet names."""

from __future__ import annotations

# Fundamental sheet names (must match İş Yatırım parquet columns)
INCOME_SHEET = "Gelir Tablosu (Çeyreklik)"
BALANCE_SHEET = "Bilanço"
CASH_FLOW_SHEET = "Nakit Akış (Çeyreklik)"

# Momentum (BUILDERS prod path)
MOMENTUM_LOOKBACK = 252
MOMENTUM_SKIP = 21
DOWNSIDE_VOL_LOOKBACK = 252

# Momentum (five_factor rotation axis)
ROTATION_MOMENTUM_LOOKBACK = 126
ROTATION_MOMENTUM_SKIP = 21

# Low volatility (BUILDERS)
LOW_VOL_LOOKBACK = 252

# Factor panels (factor_builders / core panels)
MIN_ROLLING_OBS_RATIO = 0.5
VOLATILITY_LOOKBACK_DAYS = 63
BETA_LOOKBACK_DAYS = 252
BETA_MIN_OBS = 126
VALUE_GROWTH_LOOKBACK_DAYS = 252
AMIHUD_LOOKBACK_DAYS = 21
TURNOVER_LOOKBACK_DAYS = 63
PRICE_ACCELERATION_FAST = 21
PRICE_ACCELERATION_SLOW = 63
REVERSAL_LOOKBACK_DAYS = 5
MARGIN_CHANGE_QUARTERS = 4
SALES_ACCEL_QUARTERS = 4
EARNINGS_STABILITY_QUARTERS = 8

__all__ = [
    "INCOME_SHEET",
    "BALANCE_SHEET",
    "CASH_FLOW_SHEET",
    "MOMENTUM_LOOKBACK",
    "MOMENTUM_SKIP",
    "DOWNSIDE_VOL_LOOKBACK",
    "ROTATION_MOMENTUM_LOOKBACK",
    "ROTATION_MOMENTUM_SKIP",
    "LOW_VOL_LOOKBACK",
    "MIN_ROLLING_OBS_RATIO",
    "VOLATILITY_LOOKBACK_DAYS",
    "BETA_LOOKBACK_DAYS",
    "BETA_MIN_OBS",
    "VALUE_GROWTH_LOOKBACK_DAYS",
    "AMIHUD_LOOKBACK_DAYS",
    "TURNOVER_LOOKBACK_DAYS",
    "PRICE_ACCELERATION_FAST",
    "PRICE_ACCELERATION_SLOW",
    "REVERSAL_LOOKBACK_DAYS",
    "MARGIN_CHANGE_QUARTERS",
    "SALES_ACCEL_QUARTERS",
    "EARNINGS_STABILITY_QUARTERS",
]
